# Installing Python dependencies, run syntax check and lint
# with a Python versions "3.9" and "3.10"
#
# v0.2.1

name: Test Package

on:
  # References:
  # https://docs.github.com/en/actions/learn-github-actions
  #
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code_test:
    name: Code testing

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Code check with `black`
        uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          src: "./src"
          version: "~= 22.0"
      - name: Set up Python 3.x ${{ matrix.python-version }}
        id: setup_py3x
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        # Test setup matrix by printing the current Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install package dependencies and test toolset
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./src --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
